import { readFile, writeFile, readdir } from 'node:fs/promises';
import { BUILD_VERSION_BASE } from '../assets/config.js';
const root=new URL('../',import.meta.url);
const version=BUILD_VERSION_BASE;
const modules=(await readdir(new URL('assets/',root))).filter(name=>name.endsWith('.js')).sort();
const imports=Object.fromEntries(modules.map(name=>[`/assets/${name}`,`/assets/${name}?v=${version}`]));
const map=`<script type="importmap" id="release-imports">${JSON.stringify({imports})}</script>`;
const indexUrl=new URL('index.html',root);
let html=await readFile(indexUrl,'utf8');
html=html.replace(/<script type="importmap" id="release-imports">[\s\S]*?<\/script>\n?/,'');
html=html.replace(/<script type="module" src="\/assets\/app\.js(?:\?v=[^"]*)?"><\/script>/,`${map}\n<script type="module" src="/assets/app.js?v=${version}"></script>`);
html=html.replace(/href="(\/assets\/(?:hub|overview)\.css)(?:\?v=[^"]*)?"/g,`href="$1?v=${version}"`);
await writeFile(indexUrl,html);
const cssUrl=new URL('assets/hub.css',root);
const css=await readFile(cssUrl,'utf8');
await writeFile(cssUrl,css.replace(/@import\s+(?:url\()?(['"])(?:\.\/)?tokens\.css(?:\?v=[^'"]*)?\1\)?;/,`@import url('./tokens.css?v=${version}');`));
const workerUrl=new URL('service-worker.js',root);
let worker=await readFile(workerUrl,'utf8');
worker=worker.replace(/^const CACHE=.*?;\r?\nconst SHELL=.*?;/,`const CACHE='rzsn-shell-${version}';\nconst SHELL=${JSON.stringify(['/', '/index.html',...Object.values(imports),...['hub','overview','tokens'].map(name=>`/assets/${name}.css?v=${version}`),'/assets/member/train-guide-ui.webp',`/assets/member/t10-research-guide.webp?v=${version}`,'/assets/sun.svg','/manifest.webmanifest'])};`);
worker=worker.replace('// Keep a complete code release together when an installed app is reopened.','// Versioned module URLs avoid mixed old/new code during worker upgrades.');
await writeFile(workerUrl,worker);
console.log(`Release assets stamped: ${version}; ${modules.length} modules.`);
